#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DiceRoller.Droid.Resource", IsApplication=true)]

namespace DiceRoller.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000a
			public const int Clear_Button = 2131034122;
			
			// aapt resource value: 0x7f050010
			public const int DiceItem_Layout = 2131034128;
			
			// aapt resource value: 0x7f050013
			public const int Dice_Amount = 2131034131;
			
			// aapt resource value: 0x7f050011
			public const int Dice_Icon = 2131034129;
			
			// aapt resource value: 0x7f050008
			public const int Dice_Layout = 2131034120;
			
			// aapt resource value: 0x7f050012
			public const int Dice_Name = 2131034130;
			
			// aapt resource value: 0x7f050007
			public const int Dice_Scroller = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int Die_List = 2131034118;
			
			// aapt resource value: 0x7f050014
			public const int GameItem_Layout = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int Game_Icon = 2131034133;
			
			// aapt resource value: 0x7f050005
			public const int Game_Spinner = 2131034117;
			
			// aapt resource value: 0x7f050016
			public const int Game_Title = 2131034134;
			
			// aapt resource value: 0x7f050000
			public const int Main_Layout = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public const int ResultItem_Layout = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int Result_DiceName = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int Result_DiceSide = 2131034127;
			
			// aapt resource value: 0x7f050003
			public const int Result_Grid = 2131034115;
			
			// aapt resource value: 0x7f05000e
			public const int Result_Icon = 2131034126;
			
			// aapt resource value: 0x7f050002
			public const int Results_FrameLayout = 2131034114;
			
			// aapt resource value: 0x7f05000b
			public const int Roll_Button = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int Selector_Controls = 2131034121;
			
			// aapt resource value: 0x7f050001
			public const int Selector_Fragment = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int Selector_Layout = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Activity_Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Fragment_Results = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Fragment_Selector = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Grid_ResultItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int List_DieItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Spinner_GameItem = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int lbl_result = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int welcome = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
